In [1]:
#packages and librays
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
#taking data
x=np.array([[5,7],[10,5],[15,4],[20,2],[25,8]])
y=np.array([8,4,6,2,1])

In [3]:
#Fitting Model
model=LinearRegression().fit(x,y)

In [4]:
#Predicitng Y values for Given X values (b0+(b1*x))
y_pre=model.predict(x)

In [5]:
print("Predict Score: ",model.score(x,y_pre))
print("Normal Score : ",model.score(x,y))

Predict Score:  1.0
Normal Score :  0.7824218330289029


In [6]:
#Differnce Between Y predict and Given Y
print(y_pre)
print(y)

[7.4845815  5.78414097 4.13656388 2.43612335 1.15859031]
[8 4 6 2 1]


In [7]:
#Rechecking With Formula (b0+(b1*x))
print("b0: ",model.intercept_)
print("b1: ",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x,axis=1)
print("Rechecked Y predict Values : ",y_rc)

b0:  8.709251101321586
b1:  [-0.31894273  0.05286344]
Rechecked Y predict Values :  [7.4845815  5.78414097 4.13656388 2.43612335 1.15859031]


In [8]:
#Predicitng Y values for Given X_new values (b0+(b1*x))
x_new=np.array([12,13,14,15,16,18,19,20,21,22]).reshape(-1,2)
y_new=model.predict(x_new)
print(x_new)
print(y_new)

[[12 13]
 [14 15]
 [16 18]
 [19 20]
 [21 22]]
[5.569163   5.03700441 4.55770925 3.70660793 3.17444934]


In [9]:
print("New Predict Score: ",model.score(x_new,y_new))

New Predict Score:  1.0
