In [1]:
import numpy
a1=numpy.array([1,2,3])

In [2]:
print(a1)

[1 2 3]


In [3]:
print(a1.max())

3


In [4]:
print(type(a1))

<class 'numpy.ndarray'>


In [14]:
import numpy as np
c=np.array([[1,2,3],[4,5,6]])


In [7]:
print(a2)


NameError: name 'a2' is not defined

In [8]:
print(a2)


NameError: name 'a2' is not defined

In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[4,5,6]])

In [10]:
print(a)

[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [11]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(a2)

NameError: name 'a2' is not defined

In [15]:
print(c)

[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as n
a1=n.array([1,2,3,4])

In [18]:
print(a1)

[1 2 3 4]


In [19]:
print(type(a1))

<class 'numpy.ndarray'>


In [20]:
print(a1.ndim)

1


In [21]:
a2=n.ones(4)
print(a2)

[1. 1. 1. 1.]


In [27]:
a3=n.zeros(100)
print(a3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [28]:
a4=n.tens(100)
print(a4)

AttributeError: module 'numpy' has no attribute 'tens'