In [1]:
import pandas as pd
import numpy as np
a=np.array([10,20])
b=np.array([5,10])
c=np.add(a,b)
print(c)

[15 30]


In [3]:
x=np.array([[10,20],[30,40]],dtype=complex)
x


array([[10.+0.j, 20.+0.j],
       [30.+0.j, 40.+0.j]])

In [5]:
a=np.zeroes(3,4)
a

AttributeError: module 'numpy' has no attribute 'zeroes'

In [6]:
c=np.ones(2,3,4)
c

TypeError: data type not understood

In [7]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [9]:
np.linespace(0,2,9)

AttributeError: module 'numpy' has no attribute 'Linespace'

In [11]:
a=np.random.rand(40)
a.sum(axis=0)

18.539539220606187

In [12]:
a

array([0.76945403, 0.10096724, 0.47973356, 0.43401902, 0.20198357,
       0.07459456, 0.08352965, 0.868678  , 0.15941291, 0.01773204,
       0.77903507, 0.48069949, 0.5936348 , 0.40786852, 0.78312803,
       0.29426218, 0.59061938, 0.09360774, 0.2869172 , 0.4288441 ,
       0.48204242, 0.5455265 , 0.73040339, 0.79077081, 0.9079821 ,
       0.6152083 , 0.8711139 , 0.31679631, 0.24820227, 0.75349018,
       0.75802196, 0.19910998, 0.33136533, 0.55589326, 0.64571032,
       0.01193618, 0.72457676, 0.41957488, 0.20256729, 0.50052599])

In [13]:
a.min()

0.011936181097520593

In [14]:
a.max()

0.9079820990204368

In [19]:
a=np.array([[20,30,40,50],[10,5,15,2]])
a


array([[20, 30, 40, 50],
       [10,  5, 15,  2]])

In [20]:
a.sum(axis=0)

array([30, 35, 55, 52])

In [21]:
a.sum(axis=1)

array([140,  32])

In [23]:
a.ravel()


array([20, 30, 40, 50, 10,  5, 15,  2])

In [24]:
a.flatten()

array([20, 30, 40, 50, 10,  5, 15,  2])

In [25]:
a

array([[20, 30, 40, 50],
       [10,  5, 15,  2]])

In [27]:
a.transpose()

array([[20, 10],
       [30,  5],
       [40, 15],
       [50,  2]])

In [28]:
a

array([[20, 30, 40, 50],
       [10,  5, 15,  2]])

In [31]:
a1=a.flatten()
a1[0]=99


In [32]:
a1

array([99, 99, 99, 99, 10,  5, 15,  2])

In [33]:
a

array([[99, 99, 99, 99],
       [10,  5, 15,  2]])

In [34]:
a1=a.flatten()
a1[1]=100
a1

array([ 99, 100,  99,  99,  10,   5,  15,   2])

In [35]:
a

array([[99, 99, 99, 99],
       [10,  5, 15,  2]])

In [36]:
a1=a.ravel()
a1[1]=100
a1

array([ 99, 100,  99,  99,  10,   5,  15,   2])

In [37]:
a

array([[ 99, 100,  99,  99],
       [ 10,   5,  15,   2]])

In [38]:
c=np.flip(a)

In [39]:
c

array([[  2,  15,   5,  10],
       [ 99,  99, 100,  99]])

In [40]:
a.ndim()

TypeError: 'int' object is not callable

In [41]:
np.unique(a)


array([  2,   5,  10,  15,  99, 100])